### ISSUE TITLE
Add URL to Window Title 1.01.1-pm doesn't work with PaleMoon 27.1.0b2

### ISSUE THREAD

**Issue by zaza42** [JustOff/pm27-sdk-addons#2]
I used this fancy extension with 27.0.3, but something changed in 27.1.x. Can you fix it or point me how to fix?
It does completely nothing with title. :-/

**Comment by JustOff** [comment]
27.1.x includes support for SDK-based add-ons via [PMkit](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md) so all the hacks made for 27.0.x will not required anymore. Try to install the original extension using [Moon Tester Tool](https://github.com/JustOff/moon-tester-tool) and if all is ok, ask the author to add Pale Moon support into install.rdf.

**Comment by zaza42** [comment]
;-/
![dsdccs](https://cloud.githubusercontent.com/assets/16356124/22157635/bf7b8558-df38-11e6-99a6-ca5dbeb450f1.png)

**Comment by JustOff** [comment]
I've created pull request which adds support for Pale Moon https://github.com/erichgoldman/add-url-to-window-title/pull/17, hope it will be accepted.

**Comment by zaza42** [comment]
thanx!

**Comment by JustOff** [comment]
Resolved by release [1.03](https://addons.mozilla.org/en-US/firefox/addon/add-url-to-window-title/versions/1.03).
