### ISSUE TITLE
Feedly Notifier

### ISSUE THREAD

**Issue by niceboy76** [JustOff/pm27-sdk-addons#3]
**Sorry Request**
Hello,
Would it be possible to port "Feedly Notifier" : 
https://addons.mozilla.org/addon/feedly-notifier/
so it can be run in Pale Moon 27.1 ?
Thanks in advance for your great work.
I appreciate.
Best Regards.
nice B.

**Comment by JustOff** [comment]
Have you tried to install it using Moon Tester Tool?

**Comment by niceboy76** [comment]
No. For you information, I have Palemoon version 26.5. When the version 27.0.x was out, the sdk addons are down :( and I run a test with compatchecker and Feedly Notifier was in this list : 
![sdk](https://cloud.githubusercontent.com/assets/7282830/22824044/9559b7c8-ef86-11e6-93e1-10e4b20d10d9.PNG). In this list, there are many SDK addons not compatible but the most important addon for me it's FEEDLY NOTIFIER. Thanks for your patience.

**Comment by JustOff** [comment]
You have to update Pale Moon to 27.1, no one can help you until then.
