### ISSUE TITLE
Gmail Notifier

### ISSUE THREAD

**Issue by nonamethanks** [JustOff/pm27-sdk-addons#4]
Installing [Gmail Notifier](https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/) via Moon Tester Tool does not work - Pale Moon returns the usual "This addon uses SDK" error. Am I missing something? I have tried both the latest version and the last compatible version according to mozilla.

I have already tried editing install.rdf to no avail by the way, and all the alternatives (gmail watcher, gmail sidebar) are vastly inferior and do not allow to read snippets without opening the site.

**Comment by JustOff** [comment]
Gmail Notifier uses a particular Firefox library related to Australis interface thus it isn't compatible with Pale Moon.
